### PR TITLE
Fixes multiple open issues

### PR DESCRIPTION
**Pull request by doosterkamp**
fixes DBuit/sidebar-card#14 | fixes DBuit/sidebar-card#20 | fixes DBuit/sidebar-card#21 | fixes DBuit/sidebar-card#24 | fixes DBuit/sidebar-card#25 | fixes DBuit/sidebar-card#27

- Fixes HA Top Menu is not hidden in newer versions of HA  and corrects the placement of the inner sidebar.
- Introduced a 'debug' configuration option (look at the readme.md on how to use) and some console log formatting, so the developer console stays clean by default and when developing it's more visible what messages belong to this card.
- Clicking the icon in a menu item, now also trigger the onClick event of the button
- Small change to the rollup config, to prevent it from building/including unnecessary sourcemap references
- (Re)build the sidebar on a location (url) change

### CODE REVIEW

**Comment by robsonke** [comment]
Can we get this thing merged please?

**Comment by BlackandBlue1908** [comment]
Is there a way to get these updates manually? Looks like it would fix a number of issues I am having.

**Comment by doosterkamp** [comment]
> Is there a way to get these updates manually? Looks like it would fix a number of issues I am having.

You can do a pull from my repository, but I personally prefer this to be the main repo as many people are linked to this location.

**Comment by Ixian** [comment]
I pulled your repo to try - how to implement "Use HA theme colors as default colors"?

**Comment by doosterkamp** [comment]
> I pulled your repo to try - how to implement "Use HA theme colors as default colors"?

If no additional styling is added, the Lovelace styling is inherited. So no implementation required

**Comment by Ixian** [comment]
> 
> 
> > I pulled your repo to try - how to implement "Use HA theme colors as default colors"?
> 
> If no additional styling is added, the Lovelace styling is inherited. So no implementation required

Thanks! Does this apply to custom themes? E.g. I'm running the Google Light/Dark theme but absent styling it doesn't follow it, stays a default white.

**Comment by doosterkamp** [comment]
> Thanks! Does this apply to custom themes? E.g. I'm running the Google Light/Dark theme but absent styling it doesn't follow it, stays a default white.

I haven't tested/played around with custom themes (yet), sorry ...
I'm currently a little short on private development time, but when some spare time in my calendar I will look in to it.

**Comment by darking2539** [comment]
- I use https://github.com/doosterkamp/sidebar-card repository but mutiple dashboard still not work. Could you suggest me. Bug and result show in below.


- First dashboard.
```` 
kiosk_mode:
  non_admin_settings:
    hide_header: true
    ignore_entity_settings: true
    hide_sidebar: true
sidebar:
  width:
    mobile: 0
    tablet: 25
    desktop: 20
  breakpoints:
    mobile: 768
    tablet: 1024
  clock: true
  digitalClock: true
  date: true
  hideTopMenu: true
  style: |
    :host {
        --sidebar-background: #FFF;
        --sidebar-text-color: #000;
        --face-color: #FFF;
        --face-border-color: #FFF;
        --clock-hands-color: #000;
        --clock-seconds-hand-color: #FF4B3E;
        --clock-middle-background: #FFF;
        --clock-middle-border: #000;
    }  
  title: Boss's Home
  sidebarMenu:
    - action: navigate
      navigation_path: /lovelace-floorplan/floor1  *******************************
      name: Floor Plan
      icon: mdi:floor-plan
    - action: navigate
      navigation_path: /lovelace/overview
      name: Overview
      icon: mdi:view-dashboard
      active: true
    - action: navigate
      navigation_path: /lovelace/bosss-room
      name: Boss's Room
      icon: mdi:numeric-4-circle
    - action: navigate
      navigation_path: /lovelace/settings
      name: Settings
      icon: mdi:cog
    - action: navigate
      navigation_path: /lovelace/develop
      name: Develop
      icon: mdi:hammer-screwdriver
    - action: navigate
      navigation_path: /profile
      name: Account
      icon: mdi:account
````

- Second dashboard
```` 
kiosk_mode:
  non_admin_settings:
    hide_header: true
    ignore_entity_settings: true
    hide_sidebar: true
resources:
  - url: /hacsfiles/sidebar-card/sidebar-card.js?hacstag=36314320080254
    type: module
sidebar:
  width:
    mobile: 0
    tablet: 25
    desktop: 20
  breakpoints:
    mobile: 768
    tablet: 1024
  clock: true
  digitalClock: true
  date: true
  hideTopMenu: true
  style: |
    :host {
        --sidebar-background: #FFF;
        --sidebar-text-color: #000;
        --face-color: #FFF;
        --face-border-color: #FFF;
        --clock-hands-color: #000;
        --clock-seconds-hand-color: #FF4B3E;
        --clock-middle-background: #FFF;
        --clock-middle-border: #000;
    }  
  title: Boss's Home
  sidebarMenu:
    - action: navigate
      navigation_path: /lovelace/overview
      name: Overview
      icon: mdi:view-dashboard
    - action: navigate
      navigation_path: /lovelace/bosss-room
      name: Boss's Room
      icon: mdi:numeric-4-circle
    - action: navigate
      navigation_path: /lovelace/settings
      name: Settings
      icon: mdi:cog
    - action: navigate
      navigation_path: /lovelace/develop
      name: Develop
      icon: mdi:hammer-screwdriver
    - action: navigate
      navigation_path: /profile
      name: Account
      icon: mdi:account
```` 

- Gif file (Need to refresh)
bug

**Comment by wtrbuit** [comment]
Hi @doosterkamp,

My brother built this plugin but as you might have noticed he does not really have the time to work on this. I reviewed your PR and it seems all good so I will go ahead and merge this and create a new release. I will also try to fix other open issues and keep the repo up to date for the time being.

**Pull request merged**
