### PR TITLE
Calculate the --header-height from the div#view element

### PR DESCRIPTION
**Pull request by olaoups**
We need to calculate the --header-height from the div#view element because the "kiosk-mode" module overwrite this variable as local variable and the new value is not available into div#customSidebar element.

This solves the header problem discussed here:
* https://github.com/DBuit/sidebar-card/issues/83
* https://github.com/DBuit/sidebar-card/issues/84

Tested with and without the kisok-mode, with and without header menu.

Thanks to review my code!
Cheers

### CODE REVIEW

**Comment by sparment** [comment]
@olaoups can you clarify what integration you are using that is causing the issue? I'm seeing these errors as well. Is this associated with the ["Fully Kiosk Browser" integration](https://www.home-assistant.io/integrations/fully_kiosk)? Or some other integration?

**Comment by olaoups** [comment]
@sparment I'm using [kiosk-mode](https://github.com/maykar/kiosk-mode) integration. 

I'm using this integration to disable the header menu for one user only (the dashboard user, used on my wall-tablet).

My tests for this commits are successful on:
* Firefox with/without header menu
* Chrome with/without header menu
* Fully Kiosk Browser app, but without the dedicatced integration that you mentionned.

**Comment by sparment** [comment]
@olaoups I guess my issue must be something else. The only other thing I can think of is I use [Browser Mod ](https://github.com/thomasloven/hass-browser_mod/blob/master/README.md)to hide the header menu and sidebar for a particular user. I just tried disabling those features and restarting HomeAssistant. I'm having the same issues (bottom card not showing up consistently); but I now have  just one error in the log now:

- http://192.168.1.33:8123/local/community/sidebar-card/sidebar-card.js:18125:42 TypeError: cardElement.setConfig is not a function. (In 'cardElement.setConfig(card)', 'cardElement.setConfig' is undefined)

Maybe I will wait to see if your fix solves my problems...

**Comment by olaoups** [comment]
@sparment my fix only take care of the gap on top of the sidebar when hiding the top menu with kiosk-mode integration. It will not fix any bottom display problem. I don't use the bottom card for the moment.

**Pull request merged**
